# Generated by Django 3.0.3 on 2020-03-25 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20200325_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registerform',
            name='email',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='registerform',
            name='password',
            field=models.TextField(),
        ),
    ]
