# Generated by Django 3.0.3 on 2020-03-25 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_auto_20200325_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.CharField(default='email@email.com', max_length=40),
        ),
        migrations.AddField(
            model_name='profile',
            name='password',
            field=models.CharField(default='password', max_length=30),
        ),
    ]
